project:
  type: website
  output-dir: docs

website:
  favicon: "img/favicon_gemini/favicon.ico"
  title: ""
  reader-mode: true
  navbar:
    logo: "img/logo_gemini.png"
    left:
      - text: "Research" 
        href: research.qmd
      - publications.qmd
      - text: News 
        href: news.qmd
      - text: "Team" 
        href: our_team.qmd
      - about.qmd
  page-footer:
    left: "© 2026 AG Dölken"
    center: 
      - text: "Imprint"
        href: impressum.qmd
      - text: "Privacy"
        href: datenschutz.qmd
      - text: "Contact"
        href: about.qmd#contact
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    email-obfuscation: javascript
    theme:
      light: litera
      dark: darkly
    mainfont: "Helvetica Neue, Helvetica, Arial, sans-serif"
    header-font: "Helvetica Neue, Helvetica, Arial, sans-serif"
    css: styles.css
    toc: true

editor: source
