---
title: "Our Research"
format: html
page-layout: full
bibliography: 
  - publications/Website.bib
  - publications/Website_no_Lars.bib
csl: publications/nature.csl
---

::: justified
## Systems and RNA biology of herpesvirus infections

Herpesviruses are large DNA viruses that have co-evolved with their human and animal hosts for millions of years. Eight different herpes viruses infect humans and cause a broad spectrum of diseases ranging from the common cold sores to cancer. During these millions of years of co-evolution hosts, herpesviruses learned to comprehensively modulate their host cell environment and efficiently evade the immune system. Besides representing important pathogens to human health, they represent interesting tools to study fundamental aspects of cell biology and immunology. Within their large DNA genomes, herpesviruses encode hundreds of viral proteins and peptides, many of which not only regulate a single gene, DNA or protein but interfere with complex cellular signal networks. A systems-level approach is required to see beyond the tip of the iceberg of this regulation. Our lab employs a broad range of system biology methodology and analysis tools to study host cell modulation and immune evasion in various herpesvirus models from single-cell to organismal levels.

## Herpesviral manipulation of the host transcriptional machinery

Unlike other viruses such as SARS-CoV-2, herpesviruses uniquely exploit the host’s transcriptional machinery to express their large DNA genomes. This process of cellular gene expression is subject to rapid alterations induced by both viral and antiviral mechanisms during lytic infection. Standard approaches that quantify changes in total RNA and protein levels lack the necessary temporal resolution to elucidate the underlying molecular mechanisms. Our lab has pioneered the use of metabolic labelling of newly transcribed RNA using 4-thiouridine (4sU-tagging). This innovative approach allows us to analyze short-term changes in RNA synthesis, processing and decay with superior resolution [@dolken_high-resolution_2008;@friedel_conserved_2009;@windhager_ultrashort_2012;@rutkowski_widespread_2015]. Recent improvements involving nucleotide conversion sequencing technologies [@erhard_time-resolved_2022] now enable time-resolved transcriptome analysis at single-cell resolution (scSLAM-seq[@erhard_scslam-seq_2019]). 

We are using these approaches to study how herpesviruses manipulate the host transcriptional machinery during productive and latent infection. For instance, during lytic HSV-1 infection, we discovered that HSV-1 triggers widespread, host-specific disruption of transcription termination (DoTT), leading to extensive transcriptional activity for tens of thousands of nucleotides and downstream genes [@rutkowski_widespread_2015]. We elucidated the underlying molecular mechanism and its functional consequences for productive infection [@lodha_decoding_2023]. Most recently, we could show within a consortium of international researchers that mammalian cells learned to recognize DoTT induced by HSV-1 and Influenza A virus. Specifically, DoTT results in the nuclear accumulation of long aberrant nuclear RNAs that form left-handed double-stranded RNAs, so called Z-RNAs, when spanning repetitive intergenic regions harboring endogenous retroviral elements. Host-derived Z-RNAs arising during lytic HSV-1 and IAV infection are recognized by Z-Nucleic Acid Binding Protein 1 (ZBP1), triggering cell death. Mammalian cells thus learned to exploit previous viral invasions of their large genomes to detect and efficiently combat new viral invasions [@yin_host_2025].

We are currently studying additional viral mechanisms for manipulating the cellular transcriptional machinery, the underlying molecular mechanisms, and the host defense mechanisms that detect and counteract them.

## Functional reannotation of herpesvirus genomes

Applying systems biology methodologies like RNA-seq and ribosome profiling (Ribo-seq) revealed that herpesvirus gene expression is substantially more complex. Within their 165-230kb genomes, they encode hundreds of novel transcripts and open reading frames (ORFs). Based on a broad range of systems biology data, including transcription and translation start site profiling, ribosome profiling, and quantitative proteomics, we re-annotate the genomes of HSV-1 [@whisnant_integrative_2020] as well as murine and human cytomegalovirus (MCMV/HCMV) [@erhard_improved_2018;@lodha_decoding_2023]. We also developed a new nomenclature to incorporate the novel gene products into the existing nomenclature. A particularly interesting finding from ribosome profiling experiments is the identification of hundreds of novel small herpesvirus ORFs (sORFs). Most of these are expressed upstream of previously annotated larger ORFs that represent upstream open reading frames (uORFs). Cellular uORFs are prevalent in eukaryotic genomes and constitute an important yet poorly understood regulatory network governing gene expression at the translation level. We hypothesize that viral uORFs allow these viruses to adapt viral gene expression to cell type, stress, and inflammation. Moreover, we are interested in the functional role of small viral RNAs during the different phases of the viral life cycle [@hennig_selective_2022] and their immunological role in virus control and immune evasion.

## Transcriptional regulation at the single-cell level

Single-cell RNA sequencing (scRNA-seq) has highlighted the important role of intercellular heterogeneity in phenotype variability in health and disease. Gene expression is a stochastic process, with intrinsic and extrinsic noise in transcription and translation contributing to intercellular heterogeneity in mRNA and protein levels. However, this inherent characteristic cannot be resolved using current scRNA-seq approaches. A further key limitation of all existing methods is that the RNA profile of each cell can only be analyzed once. We combined metabolic RNA labelling using 4-thiouridine with chemical nucleoside conversion and scRNA-seq to develop thiol-(SH)-linked nucleotide conversion sequencing (scSLAM-seq) [@erhard_scslam-seq_2019]. Our close collaborator Florian Erhard ([Erhard Lab](https://erhard-lab.de/)) has developed the computational approach GRAND-SLAM (Global Refined Analysis of Newly transcribed RNA and Decay rates using SLAM-seq)[@jurges_dissecting_2018] and the computational R-suite GRAND-R [@rummel_grandr_2023] to quantify the new-to-total RNA ratio (NTR) for thousands of genes in tens of thousands of cells. We are now exploiting scSLAM-seq’s super resolution to decipher virus-host interactions at the single-cell level. Our goal is to reveal novel viral and cellular mechanisms with important regulatory roles during latency, reactivation, and productive infection and develop novel means of intervention.
:::
